# Custom Language File for Launcher Customizer

[ejs.app]
title = "Endaria Launcher"

[ejs.landing]
mediaGitHubURL = "https://endaria.fr"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/SYAHDeDqCg"

[ejs.settings]
sourceGithubLink = "https://github.com/Iam-Tasic/Endaria"
supportLink = "https://github.com/Iam-Tasic/Endaria/issues"

[ejs.welcome]
welcomeHeader = "Bienvenue sur Endaria"
welcomeDescription = "Merci de vous connecter à votre compte Mojang avant de pouvoir jouer"
welcomeDescCTA = ""